[workspace]
members = ["crates/skate-core", "crates/skate-audio", "crates/skate-audio-fma", "crates/skate-data", "crates/skate-game", "crates/skate-dynamics", "crates/skate-mods", "crates/skate-net", "crates/skate-steam-relay", "crates/skate-android"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.dependencies]
bevy = { version = "=0.18.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
skate-core = { path = "crates/skate-core" }
skate-data = { path = "crates/skate-data" }

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
strip = false

[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
bevy_pbr = { path = "vendor/bevy_pbr" }
bevy_core_pipeline = { path = "vendor/bevy_core_pipeline" }
sdl3-sys = { path = "vendor/sdl3-sys" }
